# Generated by Django 3.0.3 on 2020-07-01 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='dp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('pic_url', models.CharField(default='http://itschitchat.pythonanywhere.com/media/media/default.png', max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='lastmessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myid', models.CharField(max_length=200)),
                ('fid', models.CharField(max_length=200)),
                ('cus_id', models.CharField(max_length=500)),
                ('pic_url', models.CharField(default='http://itschitchat.pythonanywhere.com/media/media/default.png', max_length=500)),
                ('f_id', models.CharField(default='a', max_length=500)),
                ('Uname', models.CharField(default='#', max_length=500)),
                ('flag', models.CharField(default='x', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='message_save',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('cus_id', models.CharField(max_length=500)),
                ('name', models.CharField(default='unavailable', max_length=500)),
                ('date', models.CharField(default='6/26/2020', max_length=30)),
                ('time', models.TextField(default='12:00', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='pic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_url', models.CharField(default='http://itschitchat.pythonanywhere.com/media/media/default.png', max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
