# Generated by Django 3.0.8 on 2020-07-18 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_auto_20200705_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='blockuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=20)),
                ('by_id', models.IntegerField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='changepassword',
            name='u_name',
        ),
        migrations.CreateModel(
            name='videocall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend', models.CharField(max_length=20)),
                ('signal', models.BooleanField(default='0')),
                ('room', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
